### ISSUE TITLE
why note readme?

### ISSUE THREAD

**Issue by Ming-XF** [robotdoly/DOLY-DIY#2]

**Comment by Ming-XF** [comment]
misspelling！Why is there no Readme？

**Comment by robotdoly** [comment]
As you know this is an ongoing project and documentation takes time. My focus is finishing the project. For now the most effective I have is located at https://www.hackster.io/robotdoly/open-doly-more-than-a-robot-d182c6 
If you want to collaborate, that would be incredibly helpful. Thanks
