### ISSUE TITLE
Does a PCB have a coordinate system for identifying component positions?"

### ISSUE THREAD

**Issue by lrmigj** [robotdoly/DOLY-DIY#5]
Does a PCB have a coordinate system for identifying component positions?"

**Comment by robotdoly** [comment]
Hi, I guess you asked a pick and place file for PCBA. Unfortunately, there isn't a file. But EasyEda project files are located in repository so you can do it via EasyEda.

**Comment by lrmigj** [comment]
OK,thank you!

**Comment by lrmigj** [comment]
Sorry, what I want is the coordinates of the SMT patch.
